Add type annotations to django.shortcuts
dmoisset/django pull request #1
Opened 2017-04-25 09:02 UTC by bartoszgrabski

2017-04-25 13:38 UTC, dmoisset requested changes
Thanks for the contribution! I reviewed some details, can you take a look at those?

2017-04-25 13:38 UTC, dmoisset commented on django/shortcuts.py
> +def redirect(to: Union[str, Any], *args: Any, **kwargs: Any) -> HttpResponseRedirect:
Shouldn't the `to` parameter allow a `Model` instead of `Any` here?

2017-04-25 13:38 UTC, dmoisset commented on django/shortcuts.py
> +def get_object_or_404(klass: Union[Model, Manager, QuerySet], *args: Any, **kwargs: Any) -> Model:
I think `klass` shouldn't be a `Model` (which mean a specific instance of a Model) but `Type[Model]` which means a Model class. Same applies to `get_list_or_404`

2017-05-05 19:52 UTC, bartoszgrabski commented on django/shortcuts.py
> +def redirect(to: Union[str, Any], *args: Any, **kwargs: Any) -> HttpResponseRedirect:
You're right.

2017-05-05 19:52 UTC, bartoszgrabski commented on django/shortcuts.py
> +def get_object_or_404(klass: Union[Model, Manager, QuerySet], *args: Any, **kwargs: Any) -> Model:
Fixed.

2017-05-05 19:54 UTC, bartoszgrabski commented
Also updated `_get_queryset` based on current annotations.

2022-02-18 19:14 UTC, closed without merging